DROP DATABASE IF EXISTS siigo_db;
CREATE DATABASE siigo_db;
USE siigo_db;

CREATE TABLE EMPRESA(
	ID_EMPRESA INT auto_increment NOT NULL,
	NOMRE_EMPRESA VARCHAR(50),
	PRIMARY KEY (ID_EMPRESA)
);

CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR INT auto_increment NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(30),
    EMAIL_PROVEEDOR VARCHAR(100),
    primary key(ID_PROVEEDOR)
);

CREATE TABLE BODEGA(
    ID_BODEGA INT auto_increment NOT NULL,
    NOMBRE_BODEGA VARCHAR(30),
    ID_PROVEEDOR_FK INT,
    primary key(ID_BODEGA),
    foreign key(ID_PROVEEDOR_FK)REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

CREATE TABLE SUCURSAL(
	ID_SUCURSAL INT auto_increment NOT NULL,
	CIUDAD VARCHAR(50),
	DIRECCION VARCHAR(50),
	ID_EMPRESA_FK INT,
	EMAIL_SUCURSAL VARCHAR(100),
	ID_BODEGA_FK INT,
	primary key(ID_SUCURSAL),
	foreign key (ID_EMPRESA_FK) REFERENCES EMPRESA(ID_EMPRESA),
	foreign key(ID_BODEGA_FK)REFERENCES BODEGA(ID_BODEGA)
);

CREATE TABLE USUARIO(
    ID_USUARIO INT  NOT NULL,
    NOMBRE_USUARIO VARCHAR(20),
    APELLIDO_USUARIO VARCHAR(20),
    EMAIL VARCHAR(30),
    password VARCHAR(200),
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT auto_increment NOT NULL,
NOMBRE_PRODUCTO VARCHAR(50),
PRECIO_PRODUCTO VARCHAR(50),
IVA DECIMAL(5, 2) DEFAULT 19.00,
PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE INVENTARIO(
ID_PRODUCTO_FK INT,
CANTIDAD_PRODUCTO VARCHAR(50),
foreign key(ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE FACTURA(
    ID_FACTURA INT auto_increment NOT NULL,
    FECHA_FACTURA datetime,
    ID_SUCURSAL_FK INT,
    primary key(ID_FACTURA),
    foreign key (ID_SUCURSAL_FK) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE DETALLE_FACTURA(
    ID_DETALLE INT auto_increment NOT NULL,
    ID_USUARIO_FK INT,
    ID_FACTURA_FK INT,
    ID_PRODUCTO_FK INT,
    CANTIDAD_DETALLE INT,
    primary key(ID_DETALLE),
    foreign key(ID_USUARIO_FK)REFERENCES USUARIO(ID_USUARIO),
	foreign key(ID_FACTURA_FK) REFERENCES FACTURA(ID_FACTURA),
    foreign key(ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO)
);
