# Generated by Django 4.2.5 on 2023-09-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'bodegas',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_persona', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_documento', models.IntegerField(blank=True, null=True)),
                ('numero_contacto', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_produccto', models.FloatField(blank=True, null=True)),
                ('iva', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(blank=True, null=True)),
                ('encola_estado', models.IntegerField(default=False)),
                ('total', models.FloatField(blank=True, null=True)),
                ('id_persona_fk', models.ForeignKey(blank=True, db_column='id_persona_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.personas')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('id_rol_fk', models.ForeignKey(blank=True, db_column='id_rol_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.roles')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_inactiva', models.IntegerField(default=False)),
                ('id_bodega_fk', models.ForeignKey(blank=True, db_column='id_bodega_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.bodegas')),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='RolesHasPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permiso_fk', models.ForeignKey(blank=True, db_column='id_permiso_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.permisos')),
                ('id_rol_fk', models.ForeignKey(blank=True, db_column='id_rol_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.roles')),
            ],
            options={
                'db_table': 'roles_has_permisos',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona_fk', models.ForeignKey(blank=True, db_column='id_persona_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.personas')),
                ('id_producto_fk', models.ForeignKey(blank=True, db_column='id_producto_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.productos')),
                ('id_sucursal_fk', models.ForeignKey(blank=True, db_column='id_sucursal_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.sucursales')),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.AddField(
            model_name='personas',
            name='id_sucursal_fk',
            field=models.ForeignKey(blank=True, db_column='id_sucursal_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.sucursales'),
        ),
        migrations.AddField(
            model_name='personas',
            name='id_usuario_fk',
            field=models.ForeignKey(blank=True, db_column='id_usuario_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.usuarios'),
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('id_bodega_fk', models.ForeignKey(blank=True, db_column='id_bodega_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.bodegas')),
                ('id_producto_fk', models.ForeignKey(blank=True, db_column='id_producto_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.productos')),
                ('id_sucursal_fk', models.ForeignKey(blank=True, db_column='id_sucursal_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.sucursales')),
            ],
            options={
                'db_table': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('id_producto_fk', models.ForeignKey(blank=True, db_column='id_producto_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.productos')),
                ('id_venta_fk', models.ForeignKey(blank=True, db_column='id_venta_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Api.ventas')),
            ],
            options={
                'db_table': 'detalle_ventas',
            },
        ),
    ]
